version: '3'

services:

  agora:
    image: "boadevops/agora:v0.23.0"
    ports:
      - "2826:2826"
      - "2827:2827"
    volumes:
      - "./agora/:/agora/"

  mysql:
    image: "mysql:8.0"
    cap_add:
      - SYS_NICE
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./stoa/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"

  stoa:
    image: "boadevops/stoa:v0.1.1"
    depends_on:
      - "agora"
      - "mysql"
    ports:
      - "3836:3836"
    volumes:
      - "./stoa/:/stoa/wd/"

  toolsdev:
    image: "boadevops/toolsdev:v0.1.0"
    depends_on:
      - "agora"
    ports:
      - "5000:5000"
    volumes:
      - "./toolsdev/:/toolsdev/wd/"
